apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: awsbedrock
spec:
  type: conversation.aws.bedrock
  metadata:
  - name: endpoint
    value: "https://bedrock-runtime.sa-east-1.amazonaws.com"
  - name: model
    value: amazon.titan-text-express-v1
  - name: cacheTTL
    value: 10m
